### ISSUE TITLE
PR10 

### ISSUE THREAD

**Issue by boscovard** [robzienert/CalendarBundle#1]
hello,

I try to install your bundle for test on PR10 when i try to access ti anyone page i have an error like :
Template name "RizzaCalendar:CalendarBundle:list.html.twig" is not valid.  ( when i try to access to /calendar/ )

it's possible i have forget something,

Any ideas.?

**Comment by robzienert** [comment]
I have not yet had the chance to update to PR10, I'll be taking a look at this as soon as possible.
