### ISSUE TITLE
Implement Recurrence for existing Doctrine DBAL entity

### ISSUE THREAD

**Issue by rvanlaak** [robzienert/CalendarBundle#20]
We'd like to make use of the `Recurrence` model for our existing "availability" implementation. Currently I'm sorting out how I can keep my existing database structure, and minimize the need for extra queries and database changes.

Currently the `Availability` items are queried based on their `dateStart` and `dateEnd`, which works when there is no `Recurrence`.

What I'd like to do is serialize the `Recurrence` entity directly into a [Doctrine object type](http://doctrine-dbal.readthedocs.org/en/latest/reference/types.html#object-types) that I'll add to the `Availability` entity. The queries that are in place can stay the same, but I'll only add an DQL WHERE that looks like 

``` sql
SELECT Availability a 
WHERE a.Recurrence IS NOT NULL 
AND a.User.id = :userId
```

After I want the controller to calculate or some of those recurring events fit in the requested timeframe.
- Will this allow me to minimize the need to unserialize the `Recurrence` and calculate extra events? 
- Or is there a better architecture to "add" recurrence to an existing events database model?
- How to mark recurring events as "finished" with this database model? Maybe something can be added to the DQL (shown above) to not return the finished recurring events?
- The Recurrence `ArrayCollection` does not seems [to be mapped for Doctrine](https://github.com/robzienert/CalendarBundle/blob/master/Resources/config/doctrine/Event.orm.xml)

**Comment by robzienert** [comment]
I don't think you should be using this bundle (I haven't touched PHP in eons, let alone this bundle); I never even finished the entirety of the domain model while I was working on this. However, if you're just looking to lift the domain model:

For anything with Recurrence, you should be scheduling an offline process to pre-calculate all of the Recurrence objects and store them into the database. Any changes to an event's recurrence collection would update the delta of what's currently stored versus the newly calculated recurrence schedule. Completely arbitrary, say you calculate out 3 months or whatever works for your use case. If anyone looks at a date past that point, you could either schedule another offline process, or calculate the recurrence schedule for that single 24 hour period on-the-fly (persisting it back into the DB).

With your recurrence schedule cached away into the database, you could do whatever sort of queries you like pretty optimally, including "finished", where the recurrence start date is EQ/LT the current time.

Good luck.

**Comment by rvanlaak** [comment]
:+1:

**Comment by mablae** [comment]
@Rvanlaak  I am not maintaining nor using this Bundle anymore.
